# -*- coding: utf-8 -*-
"""Non-expert web interface for searching the evidence reports.

Run:
    pip install -r rag/requirements.txt
    python rag/build_index.py            # one time
    streamlit run rag/app.py
Then open the browser tab it prints. Type a question in plain English and read the answer
with links to the exact source reports.
"""
import os
import streamlit as st
import rag_core as rc

st.set_page_config(page_title="KNHANES + NHANES evidence search", layout="wide")
st.title("KNHANES + NHANES evidence search")
st.caption("Ask a plain-language question. Answers are drawn only from the pre-computed reports, "
           "with the exact numbers and a link to the source report. No number is generated by a model.")

@st.cache_resource
def load_index(index_dir):
    return rc.Index(index_dir)

with st.sidebar:
    st.header("Options")
    index_dir = st.text_input("Index folder", rc.DEFAULT_INDEX)
    survey = st.selectbox("Survey", ["(both)", "KNHANES", "NHANES"])
    rtype = st.selectbox("Report type", ["(all)", "association", "trend", "ml"])
    k = st.slider("Reports to retrieve", 3, 15, 6)
    have_ollama = rc.ollama_available()
    use_llm = st.checkbox("Write a synthesized answer (needs Ollama)", value=have_ollama,
                          help="If off, the exact report excerpts are shown verbatim.")
    model = st.text_input("Ollama model", os.environ.get("LOCAL_LLM_MODEL", "llama3.2"))
    st.caption("Ollama detected" if have_ollama else "Ollama not detected - showing report excerpts")

if not os.path.exists(os.path.join(index_dir, "meta.json")):
    st.warning("No index found. Run:  python rag/build_index.py")
    st.stop()

ix = load_index(index_dir)
st.success(f"Index loaded: {ix.meta['n']:,} reports  ·  backend = {ix.meta['backend']}")

st.markdown("**Examples:** "
            "`Is uric acid associated with hypertension?` · "
            "`odds ratio for BMI and diabetes in KNHANES` · "
            "`how well can we predict metabolic syndrome?` · "
            "`trend of diabetes prevalence`")

q = st.text_input("Your question", "")
if q:
    with st.spinner("Searching the reports..."):
        res = rc.answer(q, index=ix, k=k,
                        use_llm=(True if use_llm else False), llm_model=model,
                        survey=None if survey == "(both)" else survey,
                        rtype=None if rtype == "(all)" else rtype)
    st.markdown("### Answer")
    st.write(res["answer"])
    st.markdown("### Source reports")
    for s in res["sources"]:
        st.markdown(f"- `{s['path']}`  \n  <span style='color:#888'>{s['title']} · score {s['score']:.3f}</span>",
                    unsafe_allow_html=True)
