# -*- coding: utf-8 -*-
"""
rag_core.py -- Retrieval-augmented search over the KNHANES/NHANES evidence reports.

Indexes the 7,584 self-contained Word reports in ``suppl/`` and answers plain-language
questions with the exact numbers and a citation to the source report.

Design (mirrors the manuscript, but runs with zero setup):
  * Retrieval backend:
      - ``tfidf``  (default) -- scikit-learn TF-IDF, no external service, instant.
      - ``ollama`` (optional) -- bge-m3 embeddings served locally through Ollama.
  * Answer backend:
      - Ollama (e.g. llama3.2 / llama-3.3) if reachable -> a written answer, numbers copied
        verbatim from the retrieved reports and every claim cited.
      - otherwise -> an *extractive* answer: the top reports with their exact result
        sentences and file paths (numbers are never invented).

No number is ever generated by a model; the tool only retrieves and quotes.
"""
import os, re, json, glob, pickle
import numpy as np

# ---------------------------------------------------------------- paths
HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
DEFAULT_SUPPL = os.environ.get("EVIDENCE_SUPPL", os.path.join(REPO_ROOT, "suppl"))
DEFAULT_INDEX = os.environ.get("EVIDENCE_INDEX", os.path.join(HERE, "_index"))

# ---------------------------------------------------------------- labels
def camel_to_words(s):
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", s)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", s)
    return s.strip()

# ---------------------------------------------------------------- Ollama
def _ollama_url(url=None):
    return url or os.environ.get("OLLAMA_URL", "http://localhost:11434")

def ollama_available(url=None):
    try:
        import requests
        return requests.get(_ollama_url(url) + "/api/tags", timeout=2).status_code == 200
    except Exception:
        return False

def ollama_embed(texts, model="bge-m3", url=None):
    import requests
    u = _ollama_url(url); vecs = []
    for t in texts:
        r = requests.post(u + "/api/embeddings", json={"model": model, "prompt": t}, timeout=120)
        r.raise_for_status(); vecs.append(r.json()["embedding"])
    a = np.asarray(vecs, dtype="float32")
    a /= (np.linalg.norm(a, axis=1, keepdims=True) + 1e-9)
    return a

def ollama_generate(prompt, model="llama3.2", url=None):
    import requests
    r = requests.post(_ollama_url(url) + "/api/generate",
                      json={"model": model, "prompt": prompt, "stream": False}, timeout=600)
    r.raise_for_status()
    return r.json().get("response", "").strip()

# ---------------------------------------------------------------- report parsing
def _docx_text(path, max_chars=1800):
    from docx import Document
    parts = []
    try:
        d = Document(path)
    except Exception:
        return ""
    for p in d.paragraphs:
        t = p.text.strip()
        if t:
            parts.append(t)
        if sum(len(x) for x in parts) > max_chars:
            break
    return "\n".join(parts)[:max_chars]

def _meta_from_path(path, suppl_dir):
    rel = os.path.relpath(path, suppl_dir).replace("\\", "/")
    survey = "KNHANES" if "/KNHANES/" in "/" + rel else ("NHANES" if "/NHANES/" in "/" + rel else "")
    fname = os.path.basename(path)[:-5]  # strip .docx
    if "/association/" in "/" + rel:
        rtype = "association"
        exp, rest = (fname.split("__", 1) + [""])[:2]
        out = rest.rsplit("_", 1)[0] if "_" in rest else rest
        exposure, outcome = camel_to_words(exp), camel_to_words(out)
    elif "/trend/" in "/" + rel:
        rtype = "trend"; outcome = camel_to_words(fname.split("__", 1)[0]); exposure = ""
    elif "/ml/" in "/" + rel:
        rtype = "ml"; outcome = camel_to_words(fname.split("__", 1)[0]); exposure = ""
    else:
        rtype = "other"; outcome = camel_to_words(fname); exposure = ""
    return dict(rel=rel, survey=survey, type=rtype, exposure=exposure, outcome=outcome)

def _title_for(m):
    if m["type"] == "association":
        return f"{m['exposure']} vs {m['outcome']} ({m['survey']}, association)"
    if m["type"] == "trend":
        return f"{m['outcome']} temporal trend ({m['survey']})"
    if m["type"] == "ml":
        return f"{m['outcome']} prediction model ({m['survey']})"
    return f"{m['outcome']} ({m['survey']})"

def build_records(suppl_dir=DEFAULT_SUPPL, progress=True):
    files = glob.glob(os.path.join(suppl_dir, "**", "*.docx"), recursive=True)
    files.sort()
    records = []
    for i, path in enumerate(files):
        m = _meta_from_path(path, suppl_dir)
        m["title"] = _title_for(m)
        m["text"] = _docx_text(path)
        # index string = title (weighted) + report text
        m["index_text"] = (m["title"] + ". ") * 3 + m["text"]
        m["id"] = i
        records.append(m)
        if progress and i % 500 == 0:
            print(f"  parsed {i}/{len(files)} reports", flush=True)
    return records

# ---------------------------------------------------------------- index build / load
def build_index(suppl_dir=DEFAULT_SUPPL, index_dir=DEFAULT_INDEX, backend="tfidf",
                embed_model="bge-m3"):
    os.makedirs(index_dir, exist_ok=True)
    print(f"Building evidence index from {suppl_dir}")
    records = build_records(suppl_dir)
    print(f"Parsed {len(records)} reports. Backend = {backend}")
    with open(os.path.join(index_dir, "records.jsonl"), "w", encoding="utf-8") as f:
        for r in records:
            slim = {k: r[k] for k in ("id", "rel", "survey", "type", "exposure", "outcome", "title", "text")}
            f.write(json.dumps(slim, ensure_ascii=False) + "\n")
    if backend == "ollama":
        emb = ollama_embed([r["index_text"] for r in records], model=embed_model)
        np.save(os.path.join(index_dir, "embeddings.npy"), emb)
    else:
        from sklearn.feature_extraction.text import TfidfVectorizer
        vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), min_df=2, max_features=60000)
        X = vec.fit_transform([r["index_text"] for r in records])
        with open(os.path.join(index_dir, "tfidf.pkl"), "wb") as f:
            pickle.dump(vec, f)
        import scipy.sparse as sp
        sp.save_npz(os.path.join(index_dir, "tfidf_matrix.npz"), X)
    json.dump({"backend": backend, "embed_model": embed_model, "n": len(records)},
              open(os.path.join(index_dir, "meta.json"), "w"))
    print(f"Index written to {index_dir}")
    return len(records)

class Index:
    def __init__(self, index_dir=DEFAULT_INDEX):
        self.dir = index_dir
        self.meta = json.load(open(os.path.join(index_dir, "meta.json")))
        self.records = [json.loads(l) for l in open(os.path.join(index_dir, "records.jsonl"), encoding="utf-8")]
        self.backend = self.meta["backend"]
        if self.backend == "ollama":
            self.emb = np.load(os.path.join(index_dir, "embeddings.npy"))
        else:
            import scipy.sparse as sp
            self.vec = pickle.load(open(os.path.join(index_dir, "tfidf.pkl"), "rb"))
            self.X = sp.load_npz(os.path.join(index_dir, "tfidf_matrix.npz"))

    def search(self, query, k=6, survey=None, rtype=None):
        if self.backend == "ollama":
            q = ollama_embed([query], model=self.meta["embed_model"])[0]
            scores = self.emb @ q
        else:
            from sklearn.metrics.pairwise import linear_kernel
            scores = linear_kernel(self.vec.transform([query]), self.X).ravel()
        order = np.argsort(-scores)
        out = []
        for idx in order:
            r = self.records[idx]
            if survey and r["survey"] != survey:
                continue
            if rtype and r["type"] != rtype:
                continue
            out.append({**r, "score": float(scores[idx])})
            if len(out) >= k:
                break
        return out

# ---------------------------------------------------------------- answering
GUARD = ("You answer questions about a library of pre-computed epidemiology reports. "
         "Use ONLY the report excerpts provided. Copy every number exactly as written; never "
         "compute or estimate a number. After each fact, cite the report in square brackets like "
         "[KNHANES/association/...docx]. If the excerpts do not contain the answer, say so plainly.")

def _extractive(query, hits):
    lines = [f'Top {len(hits)} reports for: "{query}"', ""]
    for h in hits:
        snippet = " ".join(h["text"].split())[:320]
        lines.append(f"• {h['title']}")
        lines.append(f"    {snippet}")
        lines.append(f"    source: {h['rel']}")
        lines.append("")
    lines.append("(No language model was used; the excerpts above are quoted verbatim from the reports.)")
    return "\n".join(lines)

def answer(query, index=None, k=6, use_llm="auto", llm_model="llama3.2", survey=None, rtype=None):
    ix = index or Index()
    hits = ix.search(query, k=k, survey=survey, rtype=rtype)
    if not hits:
        return {"answer": "No matching reports were found.", "sources": []}
    want_llm = (use_llm is True) or (use_llm == "auto" and ollama_available())
    if want_llm:
        ctx = "\n\n".join(f"[{h['rel']}] {h['title']}\n{h['text'][:900]}" for h in hits)
        prompt = f"{GUARD}\n\nReport excerpts:\n{ctx}\n\nQuestion: {query}\n\nAnswer:"
        try:
            text = ollama_generate(prompt, model=llm_model)
        except Exception as e:
            text = _extractive(query, hits) + f"\n\n(LLM unavailable: {e})"
    else:
        text = _extractive(query, hits)
    return {"answer": text, "sources": [{"title": h["title"], "path": h["rel"], "score": h["score"]} for h in hits]}
